FROM node:alpine
COPY ./package.json /app/package.json
COPY ./.env /app/.env
COPY ./.babelrc /app/.babelrc
WORKDIR /app
RUN npm install
EXPOSE 3005
VOLUME [ "/var/run/docker.sock" ]
VOLUME [ "/app/src" ]
VOLUME [ "/configs" ]
CMD ["npx", "nodemon", "--exec", "npm", "run", "babel-node", "--", "src/index.js"]